export const image = [
  "womanAccessory.png",
  "manAccessory.png",
  "womanAccessory.png",
  "manAccessory.png",
  "womanAccessory.png",
  "manAccessory.png",
  "womanAccessory.png",
  "manAccessory.png",
  "womanAccessory.png",
  "manAccessory.png",
  ,
  "womanAccessory.png",
  "manAccessory.png",
];
